[package]
name = "nebula-chat"
version = "0.1.0"
edition = "2021"
license = "BSD-2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.98"
iroh = "0.35.0"
rand = "0.8.5"
tokio = "1.45.0"
