name: nix build
on: [pull_request]
jobs:
  build:
    name: build
    strategy:
      fail-fast: false
      matrix:
        system:
          - aarch64-linux
          - x86_64-linux

    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: set up qemu
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          enable_kvm: true
          extra_nix_config: |
            extra-platforms = aarch64-linux

      - name: show flake outputs
        run: nix flake show

      - name: Building flake
        run: nix build .#packages.${{ matrix.system }}.default
